"""
TheHive Integration Service
Creates enriched cases in TheHive (or mock stub).
"""
import httpx
from app.core.config import settings


async def create_thehive_case(
    reference: str,
    subject: str,
    sender: str,
    risk_score: float,
    verdict: str,
    ioc_summary: list[dict],
) -> str | None:
    """
    Creates a TheHive case and returns the case ID, or None on failure.
    """
    severity = _verdict_to_severity(verdict)
    tags = ["phishing", f"verdict:{verdict}", f"score:{int(risk_score)}"]

    payload = {
        "title": f"[PHISHING] {subject[:80]}",
        "description": _build_description(sender, risk_score, verdict, ioc_summary),
        "severity": severity,
        "tlp": 2,  # AMBER
        "tags": tags,
        "source": "PhishingTriagePipeline",
        "sourceRef": reference,
        "flag": verdict == "malicious",
    }

    base_url = settings.mock_stub_base_url if settings.use_mock_stubs else settings.thehive_url
    endpoint = f"{base_url}/mock/thehive/case" if settings.use_mock_stubs else f"{base_url}/api/case"

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            headers = {} if settings.use_mock_stubs else {
                "Authorization": f"Bearer {settings.thehive_api_key}"
            }
            resp = await client.post(endpoint, json=payload, headers=headers)
            if resp.status_code in (200, 201):
                data = resp.json()
                return data.get("id") or data.get("_id")
    except httpx.RequestError:
        pass
    return None


def _verdict_to_severity(verdict: str) -> int:
    return {"malicious": 3, "suspicious": 2, "benign": 1, "pending": 1}.get(verdict, 1)


def _build_description(
    sender: str,
    risk_score: float,
    verdict: str,
    ioc_summary: list[dict],
) -> str:
    ioc_lines = "\n".join(
        f"  - [{i['type']}] {i['value']} (score: {i.get('risk_score', 0):.0f})"
        for i in ioc_summary[:10]
    )
    return (
        f"**Automated triage result**\n\n"
        f"- Sender: `{sender}`\n"
        f"- Risk score: **{risk_score:.1f}/100**\n"
        f"- Verdict: **{verdict.upper()}**\n\n"
        f"**IOCs ({len(ioc_summary)} total):**\n{ioc_lines}\n\n"
        f"*Generated by Phishing Triage Pipeline*"
    )
